### ISSUE TITLE
Lots of incorrect notes in the last quarter of the song.

### ISSUE THREAD

**Issue by CoreyWarren** [geraldhumphries/df-guitar-tabs#2]
I'll be going over them myself in the meantime. Lots of incorrect notes toward the end of these tabs. Lots of '0's where there should be 3s, 4s, 6s, 10s, and so on. Definitely quite confusing when I was trying to follow these and they sounded completely off, LOL.

**Comment by geraldhumphries** [comment]
Thanks for the feedback! I know you're going over them right now, but can you point out some of the places where it's incorrect in the meantime? My goal was to be 100% accurate and I thought I had it, now I'm really curious where it's wrong.

If you want, you can open a PR with the fixes. I used Guitar Pro for the .gpx and .gp5 files. Then I opened the .gp5 in TuxGuitar and exported it to txt, which missed lots of stuff like slides, bends, and mutes. It was significantly better than GP's text export at the time, but obviously not perfect. If you have a better way to do it it would be a big improvement, so you can include that in the PR as well!

It's been over a decade since I've worked on this, you will be the first person ever to suggest real fixes. :)

**Comment by CoreyWarren** [comment]
Hey, thanks for the thought-out reply. I've actually learned the full song now (still practicing!) but I think I've come to the conclusion that the tabs were accurate!

For future viewers: the song probably sounds different than how your playing will sound while sight-reading* these tabs at first. Tempo is a huge part, yes, but also, as you may know, the harmonies and rhythms in this song are unique and unconventional at times, albeit beautiful. Those '0's are actually correct. 

I recommend listening to the song as you learn the more difficult parts (last quarter of the song).

Cheers to geraldhumphries. Good work with these tabs.
